project_id = "kgambgofdizxgcdjhxlk"

[functions.send-backup-email]
verify_jwt = false
[functions.validate-promo-code]
enabled = true
verify_jwt = true
import_map = "./functions/validate-promo-code/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/validate-promo-code/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/validate-promo-code/*.html" ]
