// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// --- THIS IS THE FIX ---
// This code now reads your keys from the Vercel settings,
// instead of using the wrong, hard-coded ones.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// This check makes sure the variables are being read
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Supabase URL and Anon Key must be defined in the environment variables");
}

// 1. Declare the instance variable outside the export
let supabaseInstance: any = null;

// 2. Only create the client if it doesn't already exist
if (!supabaseInstance) {
  supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
  console.log("🛠️ Supabase Client Initialized (Locked to single instance in client.ts)");
}

// 3. Export the locked instance
export const supabase = supabaseInstance;